### ISSUE TITLE
T00001 - Create skeleton e-library-be

### ISSUE THREAD

**Issue by zaN-121** [zaN-121/e-library-be#1]
create skeleton for e-library-be

criteria

folder
1. controller
2. service
3. repository
4. util
5. model
6. config

dependencies
1. jjwt
2. springboot starter web
3. spring data jpa
4. postgresql
5. modelmaper
6. springboot validation

**Comment by ryanhasbie** [comment]
https://github.com/zaN-121/e-library-be

**Comment by ryanhasbie** [comment]
Udah beres pak Nazir

**Comment by zaN-121** [comment]
LGTM
