### ISSUE TITLE
T00012-[BE]-Penambahan validasi di awal peminjaman

### ISSUE THREAD

**Issue by Hafizsalam1** [zaN-121/e-library-be#25]
User yang meminjam tidka boleh memiliki pinjaman yang statusnya late. Satu user mempunyai maksimal 3 pinjaman yang sudah di approved, tapi belum dikembalikan. Tamahin perubahan nama enum (approved -> taken) + penmabahan method validasi pinjaman untuk admin

**Comment by zaN-121** [comment]
- [x] link pull request nya bang
